plugins {
    id 'com.diffplug.spotless' version '7.0.2' apply false
    // see https://fabricmc.net/develop/ for new versions
    id 'fabric-loom' version '1.7-SNAPSHOT' apply false
    // see https://projects.neoforged.net/neoforged/moddevgradle for new versions
    id 'net.neoforged.moddev' version '0.1.110' apply false
}

subprojects {
    apply plugin: 'com.diffplug.spotless'
    spotless {
        java {
            googleJavaFormat('1.18.1')
        }
    }
}
