plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    // Automatically enable neoforge AccessTransformers if the file exists
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.add(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
        }
        data {
            data()
        }
        server {
            server()
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
            sourceSet project(':api').sourceSets.main
        }
    }
}

sourceSets.main.compileClasspath += project(':api').sourceSets.main.output
sourceSets.main.runtimeClasspath += project(':api').sourceSets.main.output

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation project(':api')
    implementation 'com.google.code.gson:gson:2.10.1'
}

tasks.named('javadoc', Javadoc) {
    source = sourceSets.main.allJava
}
